language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

before_install:
  - gem install ruby-beautify --verbose
  - brew install python
  - pip install --upgrade autopep8
  - brew install pear
  - pear install PHP_Beautifier
