language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: sh build-package.sh

before_install:
  # Update Homebrew
  - brew update
  # Ruby language support
  - gem install ruby-beautify --verbose
  # Python language support
  - brew install python
  - pip install --upgrade autopep8
  # Markdown language support
  - brew install pandoc
  # Java, C, C++, C#, Objective-C, D, Pawn, Vala
  - brew install uncrustify
  # PHP
#  - pear install PHP_Beautifier-beta
