version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

init:
  - cmd: rd /s /q %CHOCOLATEYINSTALL%
  - ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))

install:
  - cinst atom -y
  - cd %APPVEYOR_BUILD_FOLDER%
  # Add Atom's bin (apm, etc) to PATH
  - SET PATH=%LOCALAPPDATA%\atom\bin;%PATH%
  - apm install
  # Install CLI beautifiers
  # Python
  - cinst python2 -y
  - cinst easy.install -y
  - cinst pip -y
  # autopep8
  - pip install --upgrade autopep8
  # Ruby & Gem
  - cinst ruby -y
  - gem install rubocop
  # PHP
  - cinst php -y

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  # Install languages to Atom
  - apm install language-typescript language-marko language-tss language-html-swig
  # Run tests on package
  - apm test --one --path %LOCALAPPDATA%/atom/bin/atom.cmd